### ISSUE TITLE
Make menu font size configurable

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#329]
<a href="https://github.com/aleksejrs"><img src="https://avatars.githubusercontent.com/u/1025861?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [aleksejrs](https://github.com/aleksejrs)**
_Wednesday Aug 29, 2012 at 08:07 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/329_

---

**Comment by jstetten** [comment]
>obviously it should be possible to adjust the font size in the menu

I can't wait. Is there any way us to hack this locally in the meantime?

**Comment by myrdd** [comment]
@jstetten afaik you can create a [`userChrome.css`](http://kb.mozillazine.org/index.php?title=UserChrome.css&printable=yes) file. The following could get what you want – I didn't test it though.

```css
/*
 * Do not remove the @namespace line -- it's required for correct functioning
 */
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

#rpc-main {
  font-size: 10px !important;
}
```

See also https://github.com/RequestPolicyContinued/requestpolicy/blob/v1.0.beta10/src/skin/requestpolicy.css#L13
