### ISSUE TITLE
WE port: finish "misc. refactoring" branch

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#885]
I've got a branch with many useful changes:

https://github.com/myrdd/requestpolicy/tree/feature/misc-refactoring

However, the subscription module is somehow broken:

```
console.log: [RequestPolicy] starting up
console.info: [RequestPolicy] Disabled link prefetch.
console.info: [RequestPolicy] Disabled DNS prefetch.
console.info: [RequestPolicy] Disabled Speculative pre-connections.
console.info: [RequestPolicy] [PolicyManager] loadUserRules loading user rules
console.error:
  [RequestPolicy] loadConfigAndRules():
console.dir:
  Message: TypeError: this.data is undefined
  Stack:
    getSubscriptionInfo@chrome://rpcontinued/content/lib/subscription.js:112:15
loadSubscriptionRules/pDone<@chrome://rpcontinued/content/main/requestpolicy-service.js:41:69
```

I've uploaded the built files:

* [`subscription.js`](https://pastebin.mozilla.org/9075726)
* [`requestpolicy-service.js`](https://pastebin.mozilla.org/9075727)

if someone got some time or an idea, let me know
